[package]
name = "recipemanager"
version = "0.1.1"
edition = "2024"

[dependencies]
askama = "0.16.0"
axum = { version = "0.8.9", features = ["multipart"] }
base64 = "0.22.1"
flate2 = "1.1.9"
gray_matter = "0.3.2"
pulldown-cmark = "0.13.3"
reqwest = { version = "0.13.3", features = ["json"] }
scraper = "0.26.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_yaml = "0.9.34"
slug = "0.1.6"
tokio = { version = "1.52.1", features = ["full"] }
tower-http = { version = "0.6.8", features = ["fs"] }
tracing-subscriber = "0.3.23"
uuid = { version = "1.23.1", features = ["v4"] }
zip = "8.6.0"
